version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "klassroom-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qjdtbgjoqf31"
s3_prefix = "klassroom-serverless"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
