
AWSTemplateFormatVersion: "2010-09-09"
Description: "Service to create optimized seating charts."
Transform: "AWS::Serverless-2016-10-31"
Resources:
  klassroom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambdas/klassroom
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 100
      Description: The main method for the Klassroom api
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ClassTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ClassTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SAMPLE_TABLE: !Ref ClassTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  ClassTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: class
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
